version: '3'

services:
    wp:
        image: wordpress:5.5.1-php7.3-apache
        ports:
            - 80:80
        restart: always
        env_file: .env
        volumes:
            - ./theme/:/var/www/html/wp-content/themes/theme/
            - ./uploads/:/var/www/html/wp-content/uploads/
        networks:
            - wpsite

networks:
    wpsite: {}
