version: '3'

services:
    wp:
        image: wordpress:5.5.1-php7.3-apache
        ports:
            - 1000:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wp
            WORDPRESS_DB_PASSWORD: wp
            WORDPRESS_DB_NAME: wp
        volumes:
            - ./theme/:/var/www/html/wp-content/themes/rwd
