version: '3'

services:
    wp:
        build: .
        ports:
            - 80:80
            - 443:443
        restart: always
        env_file: .env
        volumes:
            - ./theme/:/var/www/html/wp-content/themes/theme/
            - ./wp-content/uploads/:/var/www/html/wp-content/uploads/
        networks:
            - wpsite

networks:
    wpsite: {}
